### ISSUE TITLE
Use IIFE

### ISSUE THREAD

**Issue by maanlamp** [koenblezer/web-app-from-scratch-18-19#2]
https://github.com/koenblezer/web-app-from-scratch-18-19/blob/2942f5567badad87a86ed1d6fb877ea359cd3c34/week1/public/js/app.js#L35-L69

You're creating a function and calling it once. That's what IIFE's are for.

Also Fix indentation here too #1 .

**Comment by koenblezer** [comment]
Good point. Thanks!
